services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-ppassword", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      timeout: 5s
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    # entrypoint: sh -c "sleep 10 && php artisan migrate && php artisan passport:install && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"