name: Destroy Infrastructure in AWS
on:
  workflow_dispatch: # Allow manual invocation of the workflow

defaults:
  run:
    working-directory: ./

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - run: |
          aws --version
          export apprunner_arn=$(aws apprunner list-services --region eu-central-1 --query 'ServiceSummaryList[0].ServiceArn'  | sed 's![^api]*$!!' | sed 's!"!!')
          aws apprunner delete-service --service-arn ${apprunner_arn} --region eu-central-1 --no-paginate 2>&1 > /dev/null
          sleep 20
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.3"

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform fmt
          terraform init -backend-config=backend.tfvars
  
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_AWS_RDS_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_AWS_RDS_PASSWORD }}
