name: Setup infrastructure in AWS
on:
  workflow_dispatch: # Allow manual invocation of the workflow

defaults:
  run:
    working-directory: ./

jobs:
  plan:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.3"

      - name: Terraform Init
        id: init
        run: |
          terraform fmt
          terraform init
  
      - name: Terraform Apply
        run: terraform plan
  
  deploy:
    name: Terraform Deploy
    needs: plan
    runs-on: ubuntu-latest
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.3"

      - name: Terraform Init
        id: init
        run: |
          terraform fmt
          terraform init -upgrade

      - name: Terraform Apply
        run: terraform apply -auto-approve